### ISSUE TITLE
[BUG] Autorefresh in the BigSwap explorer doesn't work

### ISSUE THREAD

**Issue by MooncatDEXT** [dextools-io/community-requests#69]
### Steps

...
The autorefresh feature on the BigSwap explorer site, specifically for Ethereum, has been inactive for several months now.

### Which device are you using

- [X] Any
- [ ] Desktop Windows
- [ ] Desktop MacOS
- [ ] Desktop Linux
- [ ] Mobile browser
- [ ] App

### (if aplicable) What mobile OS device are you using?

None

### In which page do you see the problem?

https://www.dextools.io/app/en/ether/big-swap-explorer

**Comment by Sanher** [comment]
Linked to dextools-io/backend#340

**Comment by Sanher** [comment]
The problem is detected by developers and is marked as critical.  Will provide a solution ASAP.

**Comment by haivngit** [comment]
any update on this problems sir? the autorefresh on bigswap site still dosen't work

**Comment by Sanher** [comment]
> any update on this problems sir? the autorefresh on bigswap site still dosen't work

We are working in a solution ATM

**Comment by haivngit** [comment]
pls, fix it asap, it really important for dextools users to check  the volatility of the market. pls fix it asap thank u

**Comment by Sanher** [comment]
It is fixed. FYI @haivngit

**Comment by haivngit** [comment]
Hi sir the problems is still there, the autorefresh on bigswap site on
ethereum network still not working. pls check it again.

**Comment by Sanher** [comment]
@haivngit My fault, we do finish the changes necessary to refresh big swap explorer but we dont release it yet, since we have to test it.

**Comment by haivngit** [comment]
pls check and fix it. thank u
